from __future__ import annotations

import datetime as dt
from dataclasses import dataclass

from .concept_engine import Concept

MOOD_SUBTITLE = {
    "playful": "After Midnight",
    "mysterious": "Kernel Dreams in Neon",
    "heroic": "The Night Shift Protocol",
    "dreamy": "Pixel Rain at 3AM",
    "melancholic": "Echoes of an Old Workstation",
    "energetic": "Neon Boot Sequence",
}


@dataclass
class YouTubeMetadata:
    title: str
    description: str
    tags: list[str]
    pinned_comment: str
    thumbnail_text: str

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "description": self.description,
            "tags": self.tags,
            "pinned_comment": self.pinned_comment,
            "thumbnail_text": self.thumbnail_text,
        }


def _daily_index(day: dt.date) -> int:
    return day.toordinal() - dt.date(day.year, 1, 1).toordinal() + 1


def build_metadata(concept: Concept, day: dt.date, tools: str = "Python + ffmpeg") -> YouTubeMetadata:
    number = _daily_index(day)
    subtitle = MOOD_SUBTITLE.get(concept.mood, "Small Linux Night Shift")
    title = f"Server Dreams #{number:04d} — {subtitle}"
    thumbnail_text = subtitle

    tags = [
        "server dreams",
        "retro music",
        "chiptune",
        "amiga style",
        "keygen music",
        "linux art",
    ] + concept.core_keywords

    desc = (
        f"{concept.scene.title()} unfolds in a {concept.time_of_day} dream from the {concept.world.replace('_', ' ')} world.\n\n"
        "This video was automatically generated by a tiny Debian server while its owner was sleeping.\n"
        f"Date: {day.isoformat()}\n"
        f"Concept mood: {concept.mood}\n"
        f"Tools: {tools}\n\n"
        "This is an automated creative experiment where title, image, music, thumbnail, and metadata all come from one shared semantic concept.\n\n"
        "#serverdreams #chiptune #retrocomputing #demoscene"
    )

    comment = "Which dream world should the server visit next night?"
    return YouTubeMetadata(title=title, description=desc, tags=tags, pinned_comment=comment, thumbnail_text=thumbnail_text)
